/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.login;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Alumno
 */
public class Login extends javax.swing.JFrame {
    int xMouse,yMouse;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfpassword = new javax.swing.JPasswordField();
        tfusuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        entrar = new javax.swing.JPanel();
        labelAcceder = new javax.swing.JLabel();
        panelX = new javax.swing.JPanel();
        xcerrar = new javax.swing.JLabel();
        logonombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(293, 412));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        tfpassword.setBackground(new java.awt.Color(242, 242, 242));
        tfpassword.setForeground(new java.awt.Color(153, 153, 153));
        tfpassword.setText("********");
        tfpassword.setBorder(null);
        tfpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfpasswordMousePressed(evt);
            }
        });
        jPanel1.add(tfpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 190, -1));

        tfusuario.setBackground(new java.awt.Color(242, 242, 242));
        tfusuario.setForeground(new java.awt.Color(153, 153, 153));
        tfusuario.setText("mail@gmail.com");
        tfusuario.setToolTipText("");
        tfusuario.setBorder(null);
        tfusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfusuarioMousePressed(evt);
            }
        });
        jPanel1.add(tfusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 190, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("INICIAR SESIÓN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 190, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 190, 10));

        entrar.setBackground(new java.awt.Color(153, 153, 153));
        entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrarMouseExited(evt);
            }
        });

        labelAcceder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelAcceder.setForeground(new java.awt.Color(255, 255, 255));
        labelAcceder.setText("ACCEDER");
        entrar.add(labelAcceder);

        jPanel1.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 190, -1));

        panelX.setBackground(new java.awt.Color(255, 255, 255));
        panelX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelXMouseExited(evt);
            }
        });

        xcerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        xcerrar.setText("x");
        panelX.add(xcerrar);

        jPanel1.add(panelX, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 30, -1));

        logonombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.login-2.png"))); // NOI18N
        jPanel1.add(logonombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 100, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 260, 48, 260);
        jPanel2.add(jPanel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfusuarioMousePressed
        if(tfusuario.getText().equals("mail@gmail.com")){
            tfusuario.setText("");
            tfusuario.setForeground(Color.black);
        }
        
        if(String.valueOf(tfpassword.getPassword()).isEmpty()){
            tfpassword.setText("********");
            tfpassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_tfusuarioMousePressed

    private void tfpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfpasswordMousePressed
        if(String.valueOf(tfpassword.getPassword()).equals("********")){
            tfpassword.setText("");
            tfpassword.setForeground(Color.black);
        }
        
        if(tfusuario.getText().isEmpty()){
            tfusuario.setText("mail@gmail.com");
            tfusuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_tfpasswordMousePressed

    private void entrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseEntered
        entrar.setBackground(Color.red);
    }//GEN-LAST:event_entrarMouseEntered

    private void entrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseExited
        entrar.setBackground(Color.gray);
    }//GEN-LAST:event_entrarMouseExited

    private void panelXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_panelXMouseClicked

    private void panelXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelXMouseEntered
        panelX.setBackground(Color.gray);
        xcerrar.setForeground(Color.white);
        
    }//GEN-LAST:event_panelXMouseEntered

    private void panelXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelXMouseExited
        panelX.setBackground(Color.lightGray);
        xcerrar.setForeground(Color.black);
    }//GEN-LAST:event_panelXMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAcceder;
    private javax.swing.JLabel logonombre;
    private javax.swing.JPanel panelX;
    private javax.swing.JPasswordField tfpassword;
    private javax.swing.JTextField tfusuario;
    private javax.swing.JLabel xcerrar;
    // End of variables declaration//GEN-END:variables
}
